#!/bin/bash

# Build the list of extensions
#
typeset extensions=""
typeset limitExtensionsArg=""
typeset grepargs
typeset agFlags
typeset edit=false
typeset editor=emacs
typeset ECHO=""
typeset fuzzy=0
typeset caseFlag="--case-sensitive"

function DieUsage
{
	print "Usage: $0 [-x ext1] [-x ext2] [-ilvw] words to search for"
	print ""
	print "\tExample: $0 -i -x erb -x rhtml interface"
	print "\twill perform an 'ag ' on all files below the current"
	print "\tdirectory that end in either .erb or .rhtml"
	print "$*"

	exit 1
}

if [ $# -eq 0 ]
then
	DieUsage
fi

# This requires ag, so if it isn't found there is a problem
#
which ag > /dev/null
if [ $? -ne 0 ]
then
	DieUsage "\nError, ag not found, install it via:\n\tbrew install ag"
fi

while getopts "acef:ghilmnvwx:" option
do
	case $option in 
    a)
			agFlags="$agFlags --follow"
			;;
		
		c)
			grepargs="$grepargs --color"
			;;
		e)
			edit=true
			
			# Also force it to just list the files
			#            
			grepargs="$grepargs -l"
			;;
		f)
			agFlags="$agFlags -B $OPTARG -A $OPTARG" 
			;;
		i)
			caseFlag="--ignore-case"
			;;
		h)
			DieUsage
			;;
		m)
			edit=true
			editor=mate
			
			# Also force it to just list the files
			#
			grepargs="$grepargs -l"
			;;
		n)
			# No-Op, just display the command
			#
			ECHO=echo
			;;
		
		i|l|v|w)
			grepargs="$grepargs -${option}"
			;;
		
		x)
			if [ -n "$extensions" ]
			then
				extensions="$extensions|"
			fi
			extensions="$extensions$OPTARG"
	esac
done

shift $((${OPTIND} - 1)) 

if [ -n "$extensions" ]
then
    agFlags="-G .+\\.($extensions)$ $agFlags"
fi

# Don't want to expand the *'s, in case there are matching file names in this
# dir
#
set -o noglob

function doFind
{
	${ECHO} ag $caseFlag --skip-vcs-ignores --ignore _site $agFlags $grepargs "$*" 
}

if [ $edit = "true" ]
then
	# This still doesn't like file names with spaces in it.
	#
	# $editor $(doFind "$*" | sed 's/.*/"&"/' | xargs $editor)

	files=$(doFind "$*" | sed 's/.*/"&"/')
	echo $files
	eval $editor $files
else
	doFind $*
fi


exit 0

