#!/bin/ksh

# Build the list of extensions
#
typeset extentions=
typeset typelist
typeset grepargs
typeset findargs
typeset findLinks
typeset fileFilters
typeset edit=false
typeset editor=emacs
typeset ECHO=""

function DieUsage
{
	print "Usage: $0 [-x ext1] [-ilvw] words to search for"
	print ""
	print "\tExample: $0 -i -x java interface"
	print "\twill perform an 'ag --java' on all files below the current"
	print "\tdirectory that end in the java file types"
	print "$*"

	exit 1
}

if [ $# -eq 0 ]
then
	DieUsage
fi

while getopts "acef:Fgilmnvwx:" option
do
	case $option in 
		a)
			findLinks="-f"
			;;
		
		c)
			grepargs="$grepargs --color"
			;;
		e)
			edit=true
			# Also force it to just list the files                                                                                        
			grepargs="$grepargs -l"
			;;
		f)
			fileFilters="$fileFilters $OPTARG"
			;;
		m)
			edit=true
			
			# Also force it to just list the files                                  
			grepargs="$grepargs -l"
			editor=mate
			;;
		n)
			# No-Op
			#
			ECHO=echo
			;;
		
		i|l|v|w)
			grepargs="$grepargs -${option}"
			;;
		
		x)
			if [ -n "$extentions" ]
			then
				foo="$(ag --list-file-types)"
				DieUsage "Only one extension category is allowed: $foo"
				
			fi
			extentions="$extentions $OPTARG"
	esac
done

shift $((${OPTIND} - 1)) 

for extension in $extentions
do
	typelist="${typelist} --${extension}"
done

for fileFilter in $fileFilters
do
	if [ -n "$typelist" ]
	then
		typelist="$typelist -o "
	fi
	
	typelist="${typelist}-name \"${fileFilter}\""
done

findargs="$findLinks"

if [ -n "$typelist" ]
then
	findargs="$findargs $typelist"
fi

# Don't want to expand the *'s, in case there are matching file names in this
# dir
#
set -o noglob

function doFindOld
{
	${ECHO} find  . -name CVS -prune \
		-or -name .svn -prune \
		-or -name .git -prune \
		-or -name .idea -prune \
		-or -name .metadata -prune \
		-or -path '*/*.class' -prune  \
		-or -path '*/_*.java' -prune  \
		-or -name 'ossm' -prune \
		-or $(eval echo $findargs)  \
		-exec grep -H $grepargs "$*" "{}" \;
}

function doFind
{
	${ECHO} ag $findargs $grepargs "$*"
}

if [ $edit = "true" ]
then
	$editor $(doFind "$*")
else
	doFind $*
fi


exit 0

