#!/bin/bash

# Build the list of patterns
#
typeset extentions=
typeset typelist
typeset grepargs
typeset findargs
typeset findLinks
typeset edit=false
typeset editor=emacs
typeset canedit=true
typeset listLong=false
typeset followLinks=""

function DieUsage
{
	print "Usage: $0 [-x ext1 -x ext2] [-ilvw] words to search for"
	print ""
	print "\tExample: $0 -i -x sdl -x soc interface"
	print "\twill perform a 'grep -i' on all files below the current"
	print "\tdirectory that end in the pattern sdl or soc"
    print "\tYou can add a -L to follow links"

	exit 1
}

if [ $# -eq 0 ]
then
	DieUsage
fi

while getopts "aefilLmvwx:" option
do
	case $option in 
		a)
			findLinks="-o -type l"
			;;
		e)
			edit=true
			;;
		i|l|v|w)
			if [ $option = "l" ]
			then
				canedit=true
				listLong=true
			fi

			grepargs="$grepargs -${option}"
			;;
		
		L)
			followLinks="-L"
			;;
		m)
			edit=true
			editor=mate
			;;
		x)
			extentions="$extentions .$OPTARG$"
	esac
done

shift $((${OPTIND} - 1)) 

extentions="$extentions $*"

for pattern in $extentions 
do
	if [ -n "$typelist" ]
	then
		typelist="$typelist -o "
	fi

	typelist="${typelist}-name \"*${pattern}*\""
done

findargs="\( -type f $findLinks \)"

if [ -n "$typelist" ]
then
	findargs="$findargs -a \( $typelist \)"
fi

# Don't want to expand the *'s, in case there are matching file names in this
# dir
#
set -o noglob

function doFind
{
	find ${followLinks} . -path 'CVS' -prune \
		-or -path '.svn' -prune \
		-or -path 'ossm' -prune \
		-or $(eval echo $findargs) |egrep -v "/CVS/|/.svn/|.class$"
}

if [ $edit = "true" -a $canedit = "true" ]
then
	$editor $(doFind "$*")
elif [ "$listLong" = "true" ]
then

	/bin/ls -lF $(doFind "$*")
else
	doFind $* 
fi

exit 0

